# Autogenerated wrapper script for ProtocolBuffersSDK_jll for x86_64-w64-mingw32-cxx11
export libprotobuf, libprotobuf_lite, libprotobuf_lite_pkgconfig, libprotobuf_pkgconfig, libprotoc, protoc

using CompilerSupportLibraries_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ProtocolBuffersSDK")
JLLWrappers.@declare_library_product(libprotobuf, "libprotobuf.dll")
JLLWrappers.@declare_library_product(libprotobuf_lite, "libprotobuf-lite.dll")
JLLWrappers.@declare_file_product(libprotobuf_lite_pkgconfig)
JLLWrappers.@declare_file_product(libprotobuf_pkgconfig)
JLLWrappers.@declare_library_product(libprotoc, "libprotoc.dll")
JLLWrappers.@declare_executable_product(protoc)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libprotobuf,
        "bin\\libprotobuf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotobuf_lite,
        "bin\\libprotobuf-lite.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libprotobuf_lite_pkgconfig,
        "lib\\pkgconfig\\protobuf-lite.pc",
    )

    JLLWrappers.@init_file_product(
        libprotobuf_pkgconfig,
        "lib\\pkgconfig\\protobuf.pc",
    )

    JLLWrappers.@init_library_product(
        libprotoc,
        "bin\\libprotoc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        protoc,
        "bin\\protoc.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
